import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from "next/link";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
         Bienvenido al modulo de constructoras
        </h1>

        <p className={styles.description}>
          Empieza por crear un proyecto de vivienda
          <Link href="proyectos-de-viviendas/crear-proyecto"><code className={styles.code}>&rarr; /proyectos-de-viviendas/crear-proyecto</code></Link>
        </p>

        <div className={styles.grid}>
          <Link href="proyectos-de-viviendas" >
            <div className={styles.card}>
            <h2>Modulo de proyectos de viviendas &rarr;</h2>
            <p>Puedes crear, ver, eliminar los proyectos de viviendas que quieras, <strong>click aqui.</strong></p>
            </div>
          </Link>
        </div>
      </main>
    </div>
  )
}
